---
title: "Crop Yields Viz"
output:
  html_document:
    df_print: paged
---

**Data source**: Tidy Tuesday [Global crop yields](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-09-01/readme.md)

Load packages
```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(readr)
library(Hmisc)
library(skimr)
```

Get data
```{r, message = FALSE, warning = FALSE}
key_crop <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/key_crop_yields.csv')
fertilizer <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/cereal_crop_yield_vs_fertilizer_application.csv')
tractors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/cereal_yields_vs_tractor_inputs_in_agriculture.csv')
land_use <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/land_use_vs_yield_change_in_cereal_production.csv')
arable_land <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/arable_land_pin.csv')

```

Part 1 key crop yield
```{r}
skim(key_crop)
```
```{r, message = FALSE, warning = FALSE}
long_crops <- key_crop %>% 
  pivot_longer(cols = 4:last_col(),
               names_to = "crop", 
               values_to = "crop_production") %>% 
  mutate(crop = str_remove_all(crop, " \\(tonnes per hectare\\)")) %>% 
  set_names(nm = names(.) %>% tolower())
```

```{r}
colnames(long_crops)
```

Load packages for visualization
```{r, message = FALSE, warning = FALSE}
library(viridis)
library(hrbrthemes)
library(waffle)
library(magrittr)
library(ggridges)
library(ggsci)
library(ggpubr)
library(gridExtra)
```

Global key crop production throughout the years
```{r}
year_prod = long_crops %>% group_by(year) %>% tally(crop_production) %>% rename(total_production=n) %>% as.data.frame()
ggplot(year_prod, aes(x=year, y= total_production, group=1)) + geom_line() + theme_light() + labs(y="Tons per hectare", x="Year", title= "Global key crop production throughout the years")
```

```{r}

year_crop = long_crops %>% group_by(year,crop) %>% tally(crop_production) %>% rename(total_production=n) %>% as.data.frame()
ggplot(year_crop, aes(x=year, y= total_production, group=crop, fill=crop)) + geom_area() + theme_minimal() + scale_x_continuous(breaks = c(1961,2018)) + theme(panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank()) + facet_wrap(~crop) + scale_fill_simpsons() + theme(legend.position="none", axis.text.x=element_text(angle=45), axis.ticks.x = element_blank(), axis.ticks.y = element_blank()) + labs(y="Production", x="Year", title = "Global key crops production (1961-2018)")

```

Distribution of yearly production (1961-2018)
```{r, message = FALSE, warning = FALSE}
ggplot(year_crop, aes(x=total_production, y=fct_rev(crop), fill= crop)) +  geom_density_ridges() +
  theme_light() + 
  theme(legend.position = "none", panel.grid.major.y=element_blank(), panel.grid.major.x=element_blank(), panel.grid.minor.x = element_blank(), panel.border=element_blank()) + scale_fill_simpsons() + labs(y="", x="Tons per hectare", title="Distribution of yearly production (1961-2018)")
```

Production by crop type
```{r, message = FALSE, warning = FALSE}
median_values = long_crops %>% filter(!is.na(crop_production)) %>% group_by(crop) %>% summarise(med= median(crop_production, na.rm=TRUE))

ggplot(long_crops, aes(x = fct_rev(crop), y = crop_production)) +
  geom_boxplot(aes(color = crop)) +
  guides(fill = FALSE, color = FALSE) +
  coord_flip() +
  labs(y = "Tons per hectare", x = "", title = "Production by crop type") +
  theme_classic() +
  scale_color_simpsons() +
  scale_fill_simpsons()

```

Global key crops in 2018
```{r}
s1 = long_crops %>% filter(year== 2018) %>% group_by(crop) %>% tally(crop_production) %>% mutate(prop= n/sum(n)) %>% rename(fre=n) %>% as.data.frame()
s2 = c('Bananas' = 3066, 'Barley' = 390, 'Beans' = 225, 'Cassava' = 1412, 'Maize' = 1002, 'Peas'= 211, 'Potatoes' = 3883, 'Rice' = 626, 'Soybeans' = 232, 'Wheat' = 487, 'Cocoa beans' = 35)
waffle1= waffle(s2/35, rows=10, size=0.5, colors = c("#FED439FF", "#709AE1FF", "#8A9197FF", "#D2AF81FF","#FD7446FF", "#D5E4A2FF", "#197EC0FF", "#C80813FF", "#46732EFF", "#71D0F5FF", "#370355FF"), title="Global key crops in 2018") 
waffle1
```


###Fertilizers
```{r}
colnames(fertilizer)
names(fertilizer)[4] ='cereal'
names(fertilizer)[5] = 'nitrogen'
f2 = fertilizer %>% filter_at(vars(Year,cereal,nitrogen), all_vars(!is.na(.))) %>% mutate(nc = (nitrogen/cereal))
```


```{r, message = FALSE, warning = FALSE}
#scatterplot
fv1 = ggscatter(f2,x="cereal",y="nitrogen", add= "reg.line", conf.int=TRUE, cor.coef = TRUE, size = 1, alpha=0.6, add.params = list(color= "#457b9d", fill= "grey"), cor.method ="pearson",color="orange") + labs(x="Cereal yield (t/ha)", y= "Nitrogen use (kg/ha)", title = "Cereal yield and nitrogen fertilizer use") + theme(axis.title = element_text(size = 8), plot.title = element_text(size = 11), axis.text = element_text(size=9))

#nitrogen use by year
fy = f2 %>% group_by(Year) %>% summarise_at(vars(cereal, nitrogen, nc),sum) %>% as.data.frame()
fv2 = ggplot(fy, aes(x=Year, y= nitrogen, group=1)) + geom_line() + theme_light() + labs(y="Nitrogen (kg/ha)", x="Year", title= "Nitrogen fertlizer use") + theme(axis.title = element_text(size = 9), plot.title = element_text(size = 11))

#cereal yield by year
fv3 = ggplot(fy, aes(x=Year, y= cereal, group=1)) + geom_line() + theme_light() + labs(y="Cereal (t/ha)", x="Year", title= "Cereal yield") + theme(axis.title = element_text(size = 9), plot.title = element_text(size = 11))

#nitrogen/cereal
fv4 = ggplot(fy, aes(x=Year, y= nc, group=1)) + geom_line() + theme_light() + labs(y="Nitrogen (kg/ha)", x="Year", title= "Nitrogen fertilizer use per cereal yield (t/ha)") + theme(axis.title = element_text(size = 9), plot.title = element_text(size = 11))

ggarrange(fv3, fv2, fv1, fv4)
```









