---
title: "Phone Subscriptions"
output: html_notebook
---

**Notebook description**: Basic data wrangling and data visualization practice

**Data source**: Tidy Tuesday [Historical Phone Usage](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-11-10/readme.md) from OurWorldInData.org [Technology Adoption](https://ourworldindata.org/technology-adoption)

Load packages
```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(readr)
library(ggsci)
```

Import data
```{r, message = FALSE, warning = FALSE}
mobile <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/mobile.csv')
landline <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/landline.csv')
```

Join mobile and landline dataframes
```{r}
df <- inner_join(mobile, landline, by=c("code", "year", "entity", "continent", "gdp_per_cap"))
head(df)
```
UAE phone subscriptions over 30 years (inspired by tessaeagle)
```{r}
df2 <- df %>%
  filter(entity == "United Arab Emirates") %>%
  gather(key = "phoneType", value = "subs", -entity, -code, -total_pop.x, -total_pop.y, -gdp_per_cap, -continent, -year)
#find the inverse to plot divergent bars
df2$inv <-  ifelse(df2$phoneType =="landline_subs",df2$subs+1,df2$subs)
df2 <- df2 %>% mutate(inv = ifelse(phoneType =="mobile_subs",subs,subs*-1))
```

```{r}
df2 %>%
  ggplot(aes(x = year, y = inv, fill = phoneType))+
  geom_bar(stat = "identity", position = "identity")+
  geom_hline(yintercept = 0, color = "white")+
  scale_y_continuous(breaks = seq(from = -100, to = 240, by = 20), labels=abs(seq(from = -100, to = 240, by = 20)))+
  scale_x_continuous(breaks = seq(from = 1990, to = 2017, by = 5))+
  scale_fill_manual(name = "Phone Type", labels = c("Landline", "Mobile"), values = c("#606c38", "#003f88"))+
  labs(
     x = "Year",
     y = "Phone Subs per 100 People",
     fill = "Phone Type",
     title ="UAE Phone Subscriptions over Time",
     subtitle = "Comparison of Landline vs. Mobile Phone Subscriptions \n (per 100 people) in the UAE from 1990 to 2017"
   )+
   theme(
     axis.text = element_text(size = 11),
     axis.title = element_text(size = 12),
     axis.ticks.y = element_blank(),
     panel.grid = element_blank(),
     plot.title = element_text(size = 16, hjust = .5, face = "bold"),
     plot.subtitle = element_text(size = 11, hjust = .5),
     legend.background = element_blank(),
     legend.text = element_text(size = 11),
     legend.title = element_text(size = 11),
     legend.key = element_blank()
   )
```

Mobile subs by continent 
```{r}
df %>% group_by(year, continent) %>% tally(mobile_subs) %>% ggplot(aes(x=year, y=n, color=continent)) + geom_line() +
   theme(
     plot.background = element_rect(fill = "#2D2D2D"),
     panel.background = element_rect(fill = "#2D2D2D"),
     axis.text = element_text(color = "white", size = 11),
     axis.title = element_text(color = "white", size = 12),
     axis.ticks.y = element_blank(),
     axis.ticks.x = element_line(color = "white"),
     panel.grid = element_blank(),
     axis.line.x = element_line(color="white"),
     axis.line.y = element_line(color="white"),
     plot.title = element_text(color = "white", size = 16, hjust = .5, face = "bold"),
     plot.subtitle = element_text(color = "white", size = 11, hjust = .5),
     legend.background = element_blank(),
     legend.text = element_text(color = "white", size = 11),
     legend.title = element_text(color = "white", size = 11),
     legend.key = element_blank()
   ) + labs(x="Year", y="Mobile subs per 100 people", title = "Mobile subscriptions over the years", subtitle = "Comparing continents mobile subscriptions \n (per 100 people) from 1990 to 2017 ") + scale_color_tron()

```

Landline subs by continent 
```{r}
df %>% group_by(year, continent) %>% tally(landline_subs) %>% ggplot(aes(x=year, y=n, color=continent)) + geom_line() +
   theme(
     plot.background = element_rect(fill = "#2D2D2D"),
     panel.background = element_rect(fill = "#2D2D2D"),
     axis.text = element_text(color = "white", size = 11),
     axis.title = element_text(color = "white", size = 12),
     axis.ticks.y = element_blank(),
     axis.ticks.x = element_line(color = "white"),
     panel.grid = element_blank(),
     axis.line.x = element_line(color="white"),
     axis.line.y = element_line(color="white"),
     plot.title = element_text(color = "white", size = 16, hjust = .5, face = "bold"),
     plot.subtitle = element_text(color = "white", size = 11, hjust = .5),
     legend.background = element_blank(),
     legend.text = element_text(color = "white", size = 11),
     legend.title = element_text(color = "white", size = 11),
     legend.key = element_blank()
   ) + labs(x="Year", y="Landline subs per 100 people", title = "Landline subscriptions over the years", subtitle = "Comparing continents landline subscriptions \n (per 100 people) from 1990 to 2017 ") + scale_color_tron()
```



